Fixed API processing for !role and !glossary
bra1n/grimoire pull request #11
Opened 2023-04-10 15:00 UTC by phypoh

2023-04-11 20:07 UTC, bra1n requested changes
Doesn't run due to lack of `dotenv` package in package.json

2023-04-11 20:07 UTC, bra1n commented on server.js
> +require('dotenv').config()
This is not listed in the package.json - is it really needed for the bot or is it something that you use locally for development?

2023-04-12 01:39 UTC, phypoh commented on server.js
> +require('dotenv').config()
Oops. Used it locally for loading my env variables. Changed!

2023-04-21 13:53 UTC, bra1n approved these changes

2023-04-21 13:53 UTC, merged